### PR TITLE
Parameterize rpc setting with a config file

### PR DESCRIPTION
**Pull request by KanoczTomas**

### CODE REVIEW

**Comment by KanoczTomas** [comment]
Please do not merge yet, having issues with my local explorer, need to find out what causes it. But it behaves the same on master, so it is not this change. But want to be safe.

**Comment by sqrrm** [comment]
This change looks good, just let me know when you're good to merge and I'll do it.

**Comment by KanoczTomas** [comment]
You can merge it, it took a long time for someone to vote that is why it was not updating. I mistakenly thought that when bitcoind receives a block the explorer has to update the page. There were no dao related txes for more then 2.5 hours, so that is normal behavior.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Pull request merged**
